--- #YAML:1.0
name: PLP
abstract: Perl in HTML pages
version: 3.20
version_from: PLP.pm
author:
    - Mischa POSLAWSKY <perl@shiar.org>
license: mit
resources:
    homepage: http://plp.shiar.net/
    Repository: git://git.shiar.net/plp
requires:
    - perl: 5.6.0
recommends:
    - CGI::Cookie: 0
optional_features:
    - mod_perl:
        description: mod_perl backend for Apache
        requires:
            Apache::Constants: 0
	- mod_perl2:
        description: mod_perl2 backend for Apache
		requires:
			Apache2::Const: 0
			Apache2::RequestRec: 0
			Apache2::RequestUtil: 0
			Apache2::RequestIO: 0
    - FastCGI:
        description: FastCGI backend
        requires:
            FCGI: 0.61
generated_by: Mischa POSLAWSKY <perl@shiar.org>
meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
