--- #YAML:1.0
name: PLP
abstract: Perl in HTML pages
version: 3.23
version_from: PLP.pm
author:
    - Mischa POSLAWSKY <perl@shiar.org>
license: mit
resources:
    homepage: http://plp.shiar.net/
    repository: git://git.shiar.net/plp
requires:
    perl: 5.6.0
recommends:
    CGI::Cookie: 0
optional_features:
    - mod_perl:
        description: mod_perl backend for Apache
        requires:
            Apache::Constants: 0
    - mod_perl-two:
        description: mod_perl2 backend for Apache
        requires:
            Apache2::Const: 0
            Apache2::RequestRec: 0
            Apache2::RequestUtil: 0
            Apache2::RequestIO: 0
    - fastcgi:
        description: FastCGI backend
        requires:
            FCGI: 0.61
provides:
    PLP:
        file: lib/PLP.pm
        version: 3.23
    PLP::Functions:
        file: lib/PLP/Functions.pm
        version: 1.00
    PLP::Backend::Apache:
        file: lib/PLP/Backend/Apache.pm
        version: 1.00
    PLP::Backend::CGI:
        file: lib/PLP/Backend/CGI.pm
        version: 1.02
    PLP::Backend::FastCGI:
        file: lib/PLP/Backend/FastCGI.pm
        version: 1.01
    PLP::Fields:
        file: lib/PLP/Fields.pm
        version: 1.00
    PLP::Tie::Delay:
        file: lib/PLP/Tie/Delay.pm
        version: 1.00
    PLP::Tie::Headers:
        file: lib/PLP/Tie/Headers.pm
        version: 1.01
    PLP::Tie::Print:
        file: lib/PLP/Tie/Print.pm
        version: 1.00
generated_by: Mischa POSLAWSKY <perl@shiar.org>
meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
